name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install flutter
        uses: subosito/flutter-action@v1
  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: flutter pub get
      - run: flutter build web --release
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: build/web
          repository-name: grow-box/grow-box.github.io

